-- =========================================================
-- SmartEve Neon.tech Serverless PostgreSQL Schema
-- =========================================================

-- Enable UUID extension if needed
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Users Table (Synchronized with Firebase Auth)
CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(128) PRIMARY KEY,
    firebase_uid VARCHAR(128) UNIQUE NOT NULL,
    email VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'anchor', -- 'organizer', 'anchor', 'display'
    created_at BIGINT NOT NULL
);

-- 2. Events Table
CREATE TABLE IF NOT EXISTS events (
    id VARCHAR(128) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(100) NOT NULL DEFAULT 'Conference',
    date VARCHAR(50) NOT NULL,
    venue VARCHAR(255) NOT NULL,
    tone VARCHAR(100) DEFAULT 'Professional & Energetic',
    description TEXT,
    owner_id VARCHAR(128) REFERENCES users(id) ON DELETE SET NULL,
    join_code VARCHAR(16) UNIQUE NOT NULL,
    live_status VARCHAR(50) NOT NULL DEFAULT 'draft', -- 'draft', 'live', 'completed'
    current_item_id VARCHAR(128),
    started_at BIGINT,
    total_delay_min INT DEFAULT 0,
    created_at BIGINT NOT NULL
);

-- 3. Speakers Table (Cloudinary hosted photos)
CREATE TABLE IF NOT EXISTS speakers (
    id VARCHAR(128) PRIMARY KEY,
    event_id VARCHAR(128) NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    designation VARCHAR(255) NOT NULL,
    organization VARCHAR(255) NOT NULL,
    topic VARCHAR(255),
    bio TEXT,
    highlights JSONB DEFAULT '[]'::jsonb,
    photo_url TEXT, -- Cloudinary CDN URL
    status VARCHAR(50) DEFAULT 'expected' -- 'expected', 'arrived', 'absent'
);

-- 4. Agenda Items Table (Reflow engine source of truth)
CREATE TABLE IF NOT EXISTS agenda_items (
    id VARCHAR(128) PRIMARY KEY,
    event_id VARCHAR(128) NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    item_order INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL, -- 'opening', 'keynote', 'talk', 'panel', 'break', 'workshop', 'announcement', 'closing'
    speaker_ids JSONB DEFAULT '[]'::jsonb,
    duration INT NOT NULL, -- in minutes
    planned_start TIMESTAMPTZ NOT NULL,
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'upcoming', -- 'upcoming', 'live', 'done', 'cancelled', 'skipped'
    absorbable BOOLEAN DEFAULT FALSE,
    min_duration INT,
    hard_start BOOLEAN DEFAULT FALSE,
    notes TEXT,
    actual_start TIMESTAMPTZ,
    actual_end TIMESTAMPTZ
);

-- 5. Stage Scripts Table (Generated by Quad-AI or Templates)
CREATE TABLE IF NOT EXISTS stage_scripts (
    id VARCHAR(128) PRIMARY KEY,
    event_id VARCHAR(128) NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    item_id VARCHAR(128) REFERENCES agenda_items(id) ON DELETE SET NULL,
    type VARCHAR(50) NOT NULL, -- 'opening', 'welcome', 'speaker_intro', 'transition', 'delay', 'unexpected', 'closing'
    text TEXT NOT NULL,
    source VARCHAR(50) NOT NULL, -- 'ai', 'template', 'manual'
    provider VARCHAR(50), -- 'gemini', 'groq', 'nvidia', 'openrouter', 'template'
    version INT DEFAULT 1,
    created_by VARCHAR(128) NOT NULL,
    created_at BIGINT NOT NULL
);

-- 6. Event Notifications Table (FCM push notification history)
CREATE TABLE IF NOT EXISTS event_notifications (
    id VARCHAR(128) PRIMARY KEY,
    event_id VARCHAR(128) NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    type VARCHAR(50) NOT NULL, -- 'delay', 'change', 'cancel', 'announcement', 'starting', 'done'
    message TEXT NOT NULL,
    changes JSONB,
    created_by VARCHAR(128) NOT NULL,
    created_at BIGINT NOT NULL,
    priority VARCHAR(50) DEFAULT 'normal' -- 'normal', 'high', 'urgent'
);

-- 7. FCM Device Tokens Table (For Firebase push notifications to mobile anchors)
CREATE TABLE IF NOT EXISTS fcm_tokens (
    id VARCHAR(128) PRIMARY KEY,
    user_id VARCHAR(128) REFERENCES users(id) ON DELETE CASCADE,
    event_id VARCHAR(128) REFERENCES events(id) ON DELETE CASCADE,
    token TEXT NOT NULL UNIQUE,
    platform VARCHAR(50) DEFAULT 'flutter', -- 'android', 'ios', 'web'
    updated_at BIGINT NOT NULL
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_events_join_code ON events(join_code);
CREATE INDEX IF NOT EXISTS idx_agenda_event_order ON agenda_items(event_id, item_order);
CREATE INDEX IF NOT EXISTS idx_speakers_event ON speakers(event_id);
CREATE INDEX IF NOT EXISTS idx_notifications_event ON event_notifications(event_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_scripts_event ON stage_scripts(event_id);
